# Generated by Django 2.2.1 on 2019-05-09 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=30)),
                ('phone_numbers', models.CharField(max_length=10)),
                ('user_gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duckapp.TestUser')),
            ],
        ),
    ]
