# Generated by Django 2.2.1 on 2019-05-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_search_clone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_numbers',
            field=models.CharField(max_length=10),
        ),
    ]
