# Generated by Django 2.2.1 on 2019-05-09 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('google_search_clone', '0003_auto_20190509_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='google_search_clone.TestUser'),
        ),
    ]
